#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Análisis de demanda por producto.

    railway run --service Postgres python scripts/exportar_pos.py   # 1. exportar
    python scripts/analisis_producto.py                             # 2. analizar

Los descriptivos (ABC, patrón semanal, mezcla por canal) se calculan siempre.
Las métricas de predicción por producto **solo se emiten si hay historial
suficiente**; con pocos días el script lo dice y se detiene ahí, en lugar de
publicar números que parecen resultados sin serlo.
"""

import sys
from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(RAIZ))

from src import evaluacion, productos, referencias

INFORME = RAIZ / "reports" / "productos.md"


def main():
    if not productos.existe():
        print("No existe data/ventas_producto.csv.\n")
        print("Genéralo desde el POS con:")
        print("  railway run --service Postgres python scripts/exportar_pos.py\n")
        print("Ese exportador es de solo lectura y agrega producto x día en la "
              "propia base de datos.")
        return 1

    df = productos.cargar()
    res = productos.resumen(df)
    print(f"{res['filas']} filas · {res['productos']} productos · {res['dias']} días "
          f"({res['desde']} a {res['hasta']})")

    veredicto = productos.comprobar_suficiencia(df)

    abc = productos.pareto(df)
    semanal = productos.patron_semanal(df)
    canal = productos.mezcla_por_canal(df)

    clase_a = abc[abc["clase"] == "A"]
    print(f"clase A: {len(clase_a)} productos concentran "
          f"{clase_a['cuota %'].sum():.1f}% de la facturación")

    lineas = [
        "# Product-level demand",
        "",
        "Generated by `scripts/analisis_producto.py` from the POS export.",
        "",
        "## Coverage",
        "",
        f"- **{res['productos']} products** across {res['categorias']} categories",
        f"- **{res['dias']} days** with sales, {res['desde']} to {res['hasta']}",
        f"- Channels: {', '.join(res['canales'])}",
        "",
        "## ABC analysis",
        "",
        "Which products carry the revenue. Getting the forecast wrong on a class A "
        "product is not comparable to getting it wrong on a class C one.",
        "",
        abc.head(25).to_markdown(),
        "",
        "## Weekday profile of the leading products",
        "",
        semanal.to_markdown(),
        "",
        "## Product mix by channel",
        "",
        canal.head(25).to_markdown(),
        "",
        "## Forecasting",
        "",
    ]

    if not veredicto["suficiente"]:
        print(f"\nSIN MUESTRA SUFICIENTE: {veredicto['motivo']}")
        print("No se emiten métricas de predicción por producto.")
        lineas += [
            "> **Not enough history to model.**",
            ">",
            f"> {veredicto['motivo'].capitalize()}.",
            ">",
            "> Splitting the series by product multiplies the number of series and "
            "divides the sample behind each one. Fitting a model on a handful of "
            "observations per product would produce numbers that look like results "
            "without being results, so none are reported here.",
            "",
            f"The gate opens at **{veredicto['dias_minimos']} days of history** with at "
            f"least one product reaching "
            f"{productos.OBSERVACIONES_MINIMAS_POR_PRODUCTO} selling days. "
            f"Currently: {veredicto['dias']} days, "
            f"{veredicto['productos_modelables']} of {veredicto['productos_totales']} "
            "products qualify.",
            "",
        ]
    else:
        print("\nMuestra suficiente: evaluando por producto")
        filas = []
        for producto in abc[abc["clase"] == "A"].index:
            serie = productos.serie_producto(df, producto)
            if len(serie) < 40:
                continue
            fila = {"producto": producto}
            for nombre, metodo in referencias.REFERENCIAS.items():
                r = evaluacion.walk_forward(serie, metodo)
                fila[nombre] = round(evaluacion.metricas(r["real"], r["pred"])["MAE"], 2)
            filas.append(fila)
            print(f"  {producto[:34]:36} MAE {fila[referencias.PRINCIPAL]:6.2f}")

        import pandas as pd
        tabla = pd.DataFrame(filas)
        lineas += [
            "Walk-forward MAE per class A product, same protocol as the daily total: "
            "every forecast uses only earlier days.",
            "",
            tabla.to_markdown(index=False) if len(tabla) else "_no product had enough history_",
            "",
        ]

    INFORME.parent.mkdir(parents=True, exist_ok=True)
    INFORME.write_text("\n".join(lineas), encoding="utf-8")
    print(f"\ninforme en {INFORME.relative_to(RAIZ)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
