#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Pipeline completo: datos -> exploración -> referencias -> modelos -> informe.

    python scripts/run_analysis.py

Escribe las figuras en `reports/figures/` y los resultados en
`reports/resultados.md`. Es determinista: misma entrada, misma salida.
"""

import json
import sys
from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(RAIZ))

from src import caracteristicas, datos, evaluacion, graficos, modelos, referencias

FIGURAS = RAIZ / "reports" / "figures"
INFORME = RAIZ / "reports" / "resultados.md"


def main():
    FIGURAS.mkdir(parents=True, exist_ok=True)

    # --- 1. Datos -----------------------------------------------------------
    df = datos.cargar()
    res = datos.resumen(df)
    semanal = datos.por_dia_semana(df)
    print(f"[1/5] {res['observaciones']} días operativos, {res['desde']} a {res['hasta']}")

    # --- 2. Exploración -----------------------------------------------------
    graficos.serie_temporal(df, FIGURAS / "01_serie_temporal.png")
    graficos.distribucion_dia_semana(df, FIGURAS / "02_dia_semana.png")
    graficos.mezcla_canales(df, FIGURAS / "03_canales.png")
    print("[2/5] figuras exploratorias listas")

    # --- 3. Variables -------------------------------------------------------
    X = caracteristicas.construir(df)
    _, _, tabla, columnas = caracteristicas.matriz(X)
    print(f"[3/5] {len(columnas)} variables, {len(tabla)} filas con retardos completos")

    # --- 4. Walk-forward: referencias y modelos -----------------------------
    metodos = dict(referencias.REFERENCIAS)
    metodos.update(modelos.construir(tabla, columnas))

    resultados = {}
    for nombre, metodo in metodos.items():
        resultados[nombre] = evaluacion.walk_forward(df, metodo)
        m = evaluacion.metricas(resultados[nombre]["real"], resultados[nombre]["pred"])
        print(f"      {nombre:22} MAE {m['MAE']:6.2f}   MAPE {m['MAPE']:5.1f}%")

    comparativa = evaluacion.tabla_comparativa(resultados, referencias.PRINCIPAL)
    mejor = comparativa.iloc[0]["metodo"]
    mae_ref = float(comparativa.loc[comparativa["metodo"] == referencias.PRINCIPAL, "MAE"].iloc[0])
    print(f"[4/5] mejor método: {mejor}")

    graficos.comparacion_modelos(comparativa, FIGURAS / "04_comparacion.png", mae_ref)
    graficos.real_vs_prediccion(resultados[mejor], FIGURAS / "05_real_vs_pred.png", mejor)
    graficos.error_por_dia(evaluacion.error_por_dia(resultados[mejor]),
                           FIGURAS / "06_error_por_dia.png")

    imp = modelos.importancia_por_permutacion(tabla, columnas)
    graficos.importancia(imp, FIGURAS / "07_importancia.png")

    # --- 5. Informe ---------------------------------------------------------
    lo, hi = evaluacion.intervalo_bootstrap(resultados[mejor]["real"], resultados[mejor]["pred"])
    n_val = len(resultados[mejor])

    lineas = [
        "# Results",
        "",
        "Generated by `scripts/run_analysis.py`. Every number here is reproducible.",
        "",
        "## Dataset",
        "",
        f"- **{res['observaciones']} trading days**, {res['desde']} to {res['hasta']}",
        f"- Mean {res['media']}, median {res['mediana']}, std {res['desviacion']}",
        f"- Coefficient of variation **{res['coef_variacion']:.1%}**",
        f"- Range {res['minimo']} to {res['maximo']}",
        "- Channel mix: " + ", ".join(f"{k} {v:.1%}" for k, v in res["mezcla_canales"].items()),
        "",
        "## Sales by day of week",
        "",
        semanal.to_markdown(),
        "",
        "## Forecast accuracy",
        "",
        f"Walk-forward validation over **{n_val} one-step-ahead forecasts**. "
        f"Each prediction uses only data from earlier days.",
        "",
        comparativa.to_markdown(index=False),
        "",
        f"Best method: **{mejor}**, MAE 95% CI **[{lo:.2f}, {hi:.2f}]** (bootstrap, 2000 resamples).",
        "",
        "## Where the error lives",
        "",
        evaluacion.error_por_dia(resultados[mejor]).to_markdown(),
        "",
        "## Variable importance",
        "",
        imp.head(12).round(3).to_markdown(index=False),
        "",
    ]
    INFORME.parent.mkdir(parents=True, exist_ok=True)
    INFORME.write_text("\n".join(lineas), encoding="utf-8")

    (RAIZ / "reports" / "metricas.json").write_text(
        json.dumps({"resumen": res,
                    "mejor": mejor,
                    "n_validacion": n_val,
                    "ic95_mae": [round(lo, 3), round(hi, 3)],
                    "comparativa": comparativa.to_dict("records")},
                   indent=2, ensure_ascii=False),
        encoding="utf-8")

    print(f"[5/5] informe en {INFORME.relative_to(RAIZ)}")


if __name__ == "__main__":
    main()
